export type TipCategory = 'praktisch' | 'mindset' | 'partnerschaft' | 'reflexion'

export interface Tip {
  id: string
  sswFrom: number
  sswTo: number
  category: TipCategory
  emoji: string
  text: string
  detail?: string
}

export const TIPS: Tip[] = [
  // SSW 1–4 — Die ersten Wochen
  {
    id: 't01a',
    sswFrom: 1,
    sswTo: 4,
    category: 'mindset',
    emoji: '✨',
    text: 'Du trägst ein neues Leben in dir. Das ist ein Wunder — auch wenn es sich noch nicht so anfühlt. Gib dir Zeit anzukommen.',
    detail: 'Die ersten Wochen fühlen sich oft surreal an. Vielleicht zweifelst du am Test, vielleicht spürst du nichts, vielleicht ist alles auf einmal zu viel. Das ist normal. Niemand wird über Nacht zur Mutter — du wächst Tag für Tag in diese Rolle hinein. Lass dir die Zeit, die du brauchst, ohne dich für deine Gefühle zu rechtfertigen.',
  },
  {
    id: 't01b',
    sswFrom: 1,
    sswTo: 4,
    category: 'praktisch',
    emoji: '💊',
    text: 'Folsäure ist jetzt besonders wichtig. Falls du noch keine nimmst — sprich heute noch mit deiner Ärztin oder deinem Arzt.',
    detail: '400 Mikrogramm Folsäure pro Tag senken nachweislich das Risiko für Neuralrohrdefekte beim Baby. Idealerweise nimmt man sie schon vor der Schwangerschaft — aber jetzt ist immer noch früh genug. Apotheken haben sie ohne Rezept. Achte zusätzlich auf Jod und ggf. Eisen — dein Arzt kann das beim ersten Termin checken.',
  },
  {
    id: 't01c',
    sswFrom: 1,
    sswTo: 4,
    category: 'reflexion',
    emoji: '🌱',
    text: 'Wie fühlst du dich heute? Glücklich, ängstlich, überwältigt? Alle Gefühle sind erlaubt. Du musst dich nicht entscheiden.',
    detail: 'Viele Frauen erwarten von sich pures Glück — und sind dann erschrocken über Angst, Zweifel oder Wehmut über das alte Leben. Diese Ambivalenz ist nicht das Gegenteil von Liebe. Sie ist Teil davon. Du darfst dich auf dein Baby freuen UND um deine Freiheit trauern. Beides hat Platz.',
  },
  {
    id: 't01d',
    sswFrom: 1,
    sswTo: 4,
    category: 'partnerschaft',
    emoji: '💑',
    text: 'Wenn du es noch niemandem erzählt hast — das ist völlig in Ordnung. Das Geheimnis gehört euch.',
    detail: 'Diese ersten Wochen sind ein eigener kleiner Raum, in dem nur ihr beide Bescheid wisst. Nutzt das. Macht einen besonderen Spaziergang, einen ruhigen Abend, ein gemeinsames Foto, das ihr später eurem Kind zeigen könnt. Das Außen kommt schnell genug — diese Stille zu zweit kommt nicht zurück.',
  },
  {
    id: 't01e',
    sswFrom: 1,
    sswTo: 4,
    category: 'mindset',
    emoji: '🌊',
    text: 'Du musst nicht jeden Tag funktionieren. Manche Tage sind nur zum Überleben da.',
    detail: 'Wenn du im ersten Trimester um 19 Uhr ins Bett gehst, ist das keine Niederlage — das ist Hochleistungssport. Dein Körper baut gerade eine Plazenta und versorgt ein wachsendes Baby mit allem was es braucht. Das kostet ungefähr so viel Energie wie ein leichter Marathonlauf — täglich. Sei großzügig mit dir.',
  },

  // SSW 5–8 — Übelkeit & erste Anzeichen
  {
    id: 't05a',
    sswFrom: 5,
    sswTo: 8,
    category: 'praktisch',
    emoji: '🍋',
    text: 'Übelkeit? Kleine, häufige Mahlzeiten helfen oft mehr als große Portionen. Ingwertee, Salzcracker oder Zitronenduft können Linderung bringen.',
    detail: 'Ein Keks neben dem Bett — gegessen noch bevor du aufstehst — kann den Morgen komplett verändern. Salzige Cracker, trockenes Brot, eine Scheibe Toast. Der Geruch von Kaffee, Zwiebeln oder bestimmten Parfums kann Übelkeit auslösen — das ist normal und kein Zeichen von Schwäche. Wenn die Übelkeit so stark ist dass du nichts behalten kannst: bitte deinen Arzt — es gibt sichere Mittel.',
  },
  {
    id: 't05b',
    sswFrom: 5,
    sswTo: 8,
    category: 'mindset',
    emoji: '🌸',
    text: 'Übelkeit bedeutet: dein Körper arbeitet hart für das Baby. Du bist nicht schwach — du bist stark.',
    detail: 'Wissenschaftler sagen: Übelkeit ist oft ein Zeichen einer gesunden, hormonell aktiven Schwangerschaft. Es ist kein Trostpflaster — es ist ein Hinweis darauf, dass dein Körper genau das tut, was er soll. An schlechten Tagen darfst du das vergessen. Lieg auf der Couch, weine wenn du musst, und denk dran: das geht meist nach Woche 12 deutlich besser.',
  },
  {
    id: 't05c',
    sswFrom: 5,
    sswTo: 8,
    category: 'reflexion',
    emoji: '📓',
    text: 'Manche Frauen beginnen jetzt ein Schwangerschaftstagebuch. Kein Druck — aber vielleicht magst du heute einen ersten Satz schreiben?',
    detail: 'Nicht für Instagram. Nicht für dein Kind. Für dich, in zehn Jahren. Was fühlst du heute? Was macht dir Angst? Was freut dich am meisten? Schwangerschaften sind intensiv und vergehen schnell — die kleinen Gedanken verblassen als erstes. Ein Notizbuch, eine App, eine Sprachnotiz — alles zählt.',
  },
  {
    id: 't05d',
    sswFrom: 5,
    sswTo: 8,
    category: 'partnerschaft',
    emoji: '💑',
    text: 'Dein Partner weiß vielleicht nicht, wie er helfen soll. Sei konkret: "Ich brauche heute Abend Ruhe" oder "Kannst du kochen?"',
    detail: 'Partner sind keine Gedankenleser — und gerade Männer fühlen sich oft hilflos, weil sie nichts "Sichtbares" tun können. Konkrete Bitten sind ein Geschenk. "Bring mir bitte einen Tee", "Übernimm heute den Einkauf", "Halt mich einfach mal." Je klarer du sagst was du brauchst, desto entspannter werdet ihr beide.',
  },
  {
    id: 't05e',
    sswFrom: 5,
    sswTo: 8,
    category: 'praktisch',
    emoji: '☕',
    text: 'Kaffee runterfahren — aber sanft. Bis 200 mg pro Tag (eine kleine Tasse) gilt als unbedenklich.',
    detail: 'Du musst nicht von heute auf morgen alles streichen. Ein abrupter Entzug bringt Kopfschmerzen, schlechte Laune und mehr Stress als gut tut. Misch deinen Kaffee mit halb entkoffeiniertem, wechsle auf grünen Tee, oder probier mal einen Lupinen-Cappuccino. Dein Geschmack verändert sich in der Schwangerschaft sowieso — vielleicht magst du Kaffee bald gar nicht mehr.',
  },

  // SSW 9–12 — Erstes Trimester Endspurt
  {
    id: 't09a',
    sswFrom: 9,
    sswTo: 12,
    category: 'praktisch',
    emoji: '🏥',
    text: 'Der erste große Ultraschall steht bald an. Schreib deine Fragen für die Ärztin schon jetzt auf — damit du im Moment nichts vergisst.',
    detail: 'Im Behandlungszimmer ist man oft aufgeregt und vergisst die Hälfte. Mach dir vorher Notizen auf dem Handy: Wie ist der Mutterpass zu lesen? Wann darf ich reisen? Welche Sportarten sind ok? Was ist mit Sex? Welche Symptome sollten sofort gemeldet werden? Niemand findet diese Fragen dumm — und du bekommst die Antworten nur wenn du fragst.',
  },
  {
    id: 't09b',
    sswFrom: 9,
    sswTo: 12,
    category: 'mindset',
    emoji: '🌙',
    text: 'Erschöpfung im ersten Trimester ist real und normal. Dein Körper baut gerade eine Plazenta auf. Ruh dich aus, wann immer du kannst.',
    detail: 'Die Plazenta ist ein komplettes neues Organ, das dein Körper aus dem Nichts wachsen lässt — ein Wunder der Biologie. Sobald sie fertig ist (meist um Woche 12-14), übernimmt sie viel Arbeit, und du fühlst dich oft schlagartig besser. Bis dahin: 10-Minuten-Powernaps am Mittag, früher ins Bett, weniger Verabredungen. Niemand wird das später hinterfragen.',
  },
  {
    id: 't09c',
    sswFrom: 9,
    sswTo: 12,
    category: 'reflexion',
    emoji: '💭',
    text: 'Wann möchtest du es wem sagen? Überleg heute, wer die erste Person sein soll, die es erfährt — außer euch beiden.',
    detail: 'Manche warten bis nach dem 12-Wochen-Ultraschall, andere brauchen sofort eine Vertraute. Beides ist richtig. Denk dran: Wer es weiß, weiß es auch im Falle einer Fehlgeburt. Wähle Menschen, die dich tragen würden — nicht nur die, die sich freuen würden. Das ist ein Unterschied.',
  },
  {
    id: 't09d',
    sswFrom: 9,
    sswTo: 12,
    category: 'partnerschaft',
    emoji: '💑',
    text: 'Bald könnt ihr das erste Mal gemeinsam das Herzchen schlagen hören. Ein Moment, den ihr nicht vergessen werdet.',
    detail: 'Plant den Termin so, dass dein Partner mitkommen kann — auch wenn es Urlaub kostet oder eine Schicht getauscht werden muss. Dieser kleine, schnelle Ton aus dem Ultraschall macht etwas mit Vätern: Vorher abstrakt, danach plötzlich real. Es ist oft DER Moment, in dem aus "Schwangerschaft" "unser Baby" wird.',
  },
  {
    id: 't09e',
    sswFrom: 9,
    sswTo: 12,
    category: 'praktisch',
    emoji: '🩺',
    text: 'Mutterpass immer dabei haben — er ist deine medizinische Visitenkarte für jede Notfallsituation.',
    detail: 'Pack ihn in deine Handtasche, nicht in den Schrank. Im Zweifelsfall (Blutungen, Unfall, Reise) brauchst du ihn sofort. Auf Reisen idealerweise zusätzlich ein Foto der wichtigsten Seiten auf dem Handy — falls die Tasche mal verloren geht. Klingt übertrieben, ist aber gold wert wenn der Fall eintritt.',
  },

  // SSW 13–16 — Zweites Trimester beginnt
  {
    id: 't13a',
    sswFrom: 13,
    sswTo: 16,
    category: 'mindset',
    emoji: '🌈',
    text: 'Willkommen im zweiten Trimester! Viele Frauen beschreiben es als die schönste Phase. Die Übelkeit lässt nach — die Vorfreude wächst.',
    detail: 'Das zweite Trimester wird oft "Honeymoon-Phase" genannt — und das ist kein Zufall. Hormone stabilisieren sich, der Bauch ist sichtbar aber nicht störend, du hast wieder Energie. Nutze diese Wochen für alles, was später schwerer wird: Reisen, Restaurantbesuche, lange Spaziergänge, gemeinsame Zeit. Das dritte Trimester kommt schneller als du denkst.',
  },
  {
    id: 't13b',
    sswFrom: 13,
    sswTo: 16,
    category: 'praktisch',
    emoji: '📋',
    text: 'Jetzt ist ein guter Zeitpunkt, sich um einen Platz in einem Geburtsvorbereitungskurs zu kümmern. Die beliebtesten sind schnell ausgebucht.',
    detail: 'Hebammen-Kurse, Hypnobirthing, Wassergymnastik — die Auswahl ist groß. Frag in der Hebammenpraxis, in deiner Klinik oder bei Freundinnen mit Kindern. Die Kosten übernimmt meist die Krankenkasse für dich (Partner manchmal nicht). Wichtig: Kurse für werdende Eltern starten oft in SSW 28 — aber Anmeldung ist jetzt.',
  },
  {
    id: 't13c',
    sswFrom: 13,
    sswTo: 16,
    category: 'reflexion',
    emoji: '🌿',
    text: 'Was ist dein größter Wunsch für die Geburt? Noch kein Plan nötig — aber fang an, dir Gedanken zu machen.',
    detail: 'Vielleicht: "Ich möchte mich sicher fühlen." "Ich möchte aktiv sein dürfen." "Ich möchte, dass mein Partner an meiner Seite ist." Wünsche sind keine Pläne — sie sind dein innerer Kompass. Aus dem ersten Wunsch ergeben sich später automatisch die richtigen Fragen für den Geburtsplan-Wizard.',
  },
  {
    id: 't13d',
    sswFrom: 13,
    sswTo: 16,
    category: 'partnerschaft',
    emoji: '💑',
    text: 'Teile deinem Partner heute eine Seite aus unserem Geburtsplan-Wizard. Gemeinsam darüber nachdenken schafft Nähe.',
    detail: 'Geburtsplan ist nicht nur deine Aufgabe. Wenn dein Partner sich früh mit den Fragen beschäftigt, ist er/sie im entscheidenden Moment vorbereitet — und kann für dich sprechen, wenn du nicht kannst. Macht einen "Geburtsplan-Abend" daraus: ein Glas (alkoholfreier) Sekt, Snacks, und gemeinsam durch den Wizard scrollen.',
  },
  {
    id: 't13e',
    sswFrom: 13,
    sswTo: 20,
    category: 'reflexion',
    emoji: '📝',
    text: 'Fang heute ein Schwangerschaftstagebuch an — auch wenn es nur 3 Sätze sind.',
    detail: 'Nicht für Instagram. Nicht für dein Kind. Für dich, in zehn Jahren. Was fühlst du heute? Was macht dir Angst? Was freut dich am meisten? Schwangerschaften sind intensiv und vergehen schnell — die kleinen Gedanken verblassen als erstes. Ein Notizbuch, eine App, ein Sprachnotiz — alles zählt.',
  },

  // SSW 17–20 — Baby bewegt sich
  {
    id: 't17a',
    sswFrom: 17,
    sswTo: 20,
    category: 'mindset',
    emoji: '🦋',
    text: 'Bald wirst du die ersten Kindsbewegungen spüren — oft wie ein Kribbeln oder Flattern. Sei geduldig, sie kommen.',
    detail: 'Erstgebärende spüren sie meist zwischen SSW 18 und 22 — manche früher, manche später. Es fühlt sich nicht wie ein Tritt an, sondern wie kleine Bläschen oder ein Fisch im Bauch. Wenn du gestresst bist, im Stehen oder beim Sport: oft spürt man nichts. Leg dich ruhig hin, lege die Hände auf den Bauch, atme. Dann kommen sie.',
  },
  {
    id: 't17b',
    sswFrom: 17,
    sswTo: 20,
    category: 'praktisch',
    emoji: '👩‍⚕️',
    text: 'Ab SSW 20 empfiehlt es sich, eine Hebamme für die Nachsorge zu suchen. Gute Hebammen sind schnell vergeben — früh anfragen lohnt sich.',
    detail: 'Schreib mehrere Hebammen gleichzeitig an — die meisten haben volle Auftragsbücher und antworten nicht immer. In ländlichen Regionen kann es knapp werden, in Großstädten manchmal monatelange Wartelisten. Plattformen wie hebammensuche.de, ammely oder lokale Hebammenverbände helfen. Frag auch in deiner Frauenarztpraxis nach Empfehlungen.',
  },
  {
    id: 't17c',
    sswFrom: 17,
    sswTo: 20,
    category: 'reflexion',
    emoji: '💭',
    text: 'Wie stellst du dir den ersten Tag mit dem Baby vor? Kein richtiges oder falsches Bild — lass deiner Fantasie freien Lauf.',
    detail: 'Manche sehen sich auf dem Sofa kuscheln, andere im Park, andere total überfordert mit nassem Haar und Müsli im Gesicht. Alle Bilder sind gültig — und keines wird genau so eintreten. Aber das innere Bild zu haben hilft, eigene Erwartungen zu erkennen. Schreib es auf — und schau in einem Jahr darauf zurück.',
  },
  {
    id: 't17d',
    sswFrom: 17,
    sswTo: 20,
    category: 'partnerschaft',
    emoji: '💑',
    text: 'Wenn du die ersten Bewegungen spürst, leg die Hand deines Partners auf deinen Bauch. Diesen Moment werdet ihr beide nie vergessen.',
    detail: 'Anfangs sind die Bewegungen für andere noch nicht spürbar — auch nicht für den Partner. Das ändert sich meist um SSW 22-24. Bis dahin: erzähl ihm/ihr trotzdem davon. "Gerade hat es sich gemeldet." Das macht das Baby auch für den Partner real, lange bevor er/sie etwas spürt.',
  },
  {
    id: 't17e',
    sswFrom: 17,
    sswTo: 20,
    category: 'praktisch',
    emoji: '🛏️',
    text: 'Schlaf jetzt am besten auf der linken Seite — das verbessert die Durchblutung der Plazenta.',
    detail: 'Auf dem Rücken kann ab dem zweiten Trimester die untere Hohlvene zusammengedrückt werden — das wird unangenehm. Die linke Seitenlage gilt als optimal. Ein Schwangerschaftskissen (zwischen den Knien, unter dem Bauch) macht einen Riesenunterschied. Es muss kein 100-Euro-Modell sein — auch ein langes normales Kissen tut es.',
  },

  // SSW 21–24 — Mitte der Schwangerschaft
  {
    id: 't21a',
    sswFrom: 21,
    sswTo: 24,
    category: 'mindset',
    emoji: '🌺',
    text: 'Dein Bauch wächst sichtbar. Manche lieben das — andere brauchen etwas Zeit. Beides ist vollkommen normal.',
    detail: 'Wenn du dich in deinem Körper fremd fühlst, bist du nicht allein. Dehnungsstreifen, Wassereinlagerungen, eine breitere Nase, dunklere Brustwarzen — vieles ändert sich. Manche dieser Änderungen bleiben, viele gehen wieder. Aber dein Körper macht gerade etwas Außergewöhnliches. Versuch ihm zu danken, auch wenn du ihn nicht jeden Tag liebst.',
  },
  {
    id: 't21b',
    sswFrom: 21,
    sswTo: 24,
    category: 'praktisch',
    emoji: '💧',
    text: 'Genug trinken ist jetzt besonders wichtig. 2–3 Liter Wasser täglich helfen gegen Schwellungen, Müdigkeit und Kreislaufprobleme.',
    detail: 'Wenn du oft Kopfschmerzen oder Krämpfe in den Waden hast — meist ist es zu wenig getrunken. Hilfreicher Trick: stell dir morgens 2 Liter-Flaschen hin und trink sie über den Tag leer. So musst du nicht zählen. Tee, Saftschorle und wasserreiche Lebensmittel (Gurke, Melone) zählen mit.',
  },
  {
    id: 't21c',
    sswFrom: 21,
    sswTo: 24,
    category: 'reflexion',
    emoji: '🌸',
    text: 'Was macht dich heute stolz auf dich und deinen Körper? Schreib es auf oder sag es laut — du verdienst dieses Lob.',
    detail: 'Wir sind gewohnt, unseren Körper zu kritisieren. Schwangerschaft ist eine seltene Chance, ihn zu bewundern. Was kann er gerade? Wachsen lassen, nähren, schützen. Sag dir: "Danke, dass du das machst." Klingt komisch, wirkt aber. Selbstmitgefühl ist eine Fähigkeit — und Schwangerschaft ist ein guter Trainingsplatz.',
  },
  {
    id: 't21d',
    sswFrom: 21,
    sswTo: 24,
    category: 'partnerschaft',
    emoji: '💑',
    text: 'Plant heute einen gemeinsamen Abend ohne Handy. Reden, träumen, Namen überlegen — einfach zu zweit sein.',
    detail: 'Nehmt einen Stift und schreibt jeder eure 5 Lieblingsnamen auf — ohne vorher abzusprechen. Manche Paare entdecken so einen, der bei beiden auf der Liste steht. Außerdem: redet über kleine Erinnerungen aus eurer eigenen Kindheit. Was war wichtig? Was wollt ihr weitergeben? Was nicht? Solche Gespräche kosten nichts und schaffen tiefe Nähe.',
  },
  {
    id: 't21e',
    sswFrom: 21,
    sswTo: 24,
    category: 'praktisch',
    emoji: '👶',
    text: 'Mutterschutzantrag und Elterngeld früh vorbereiten — die Bürokratie braucht Zeit.',
    detail: 'Mutterschutz beginnt 6 Wochen vor dem ETT. Elterngeld kann erst nach der Geburt beantragt werden, aber alle Unterlagen kannst du jetzt schon zusammenstellen: Lohnabrechnungen der letzten 12 Monate, Geburtsurkunde des Babys (kommt später), Steuerbescheid, Bankverbindung. Manche Bundesländer haben Online-Tools, die das stark vereinfachen.',
  },

  // SSW 25–28 — Drittes Trimester naht
  {
    id: 't25a',
    sswFrom: 25,
    sswTo: 28,
    category: 'praktisch',
    emoji: '🎒',
    text: 'Denk schon mal an die Krankentasche. Du musst sie noch nicht packen — aber eine Liste zu erstellen nimmt später Stress.',
    detail: 'Drei Bereiche: für dich (bequeme Kleidung, Stilleinlagen, Hausschuhe, Pflege ohne Duft, Snacks), fürs Baby (zwei Strampler, Mützchen, eine Decke, Erstausstattung-Body), für den Partner (Snacks, Powerbank, Wechselshirt). Vergiss Mutterpass, Personalausweis und Versichertenkarte nicht — sie kommen am besten ganz nach oben.',
  },
  {
    id: 't25b',
    sswFrom: 25,
    sswTo: 28,
    category: 'mindset',
    emoji: '💪',
    text: 'Du trägst nicht nur ein Kind — du wächst selbst. Dein Mut, deine Stärke, deine Liebe werden größer als du dachtest.',
    detail: 'Du wirst Dinge schaffen, die du dir heute nicht zutraust. Drei Stunden Schlaf am Stück und trotzdem ein lachendes Baby trösten. Wundverbände wechseln, ohne dabei selbst umzukippen. Eine Geburt durchstehen — wie auch immer sie kommt. Mutterschaft offenbart eine Kraft in dir, die du noch nicht kanntest. Vertrau darauf.',
  },
  {
    id: 't25c',
    sswFrom: 25,
    sswTo: 28,
    category: 'reflexion',
    emoji: '🌙',
    text: 'Schläfst du schlecht? Das ist normal. Versuch es mit einem Schwangerschaftskissen und einer Tasse Kamillentee vor dem Schlafen.',
    detail: 'Ab dem dritten Trimester ist Schlaf eine echte Herausforderung. Der Bauch drückt, der Rücken zieht, das Baby tritt nachts. Routinen helfen: gleiche Schlafenszeit, Handy aus dem Schlafzimmer, kühles Zimmer (18°C ideal). Wenn du nachts wach liegst — kein Drama. Aufstehen, Tee trinken, ein paar Seiten lesen, dann zurück. Erzwungener Schlaf wird nicht besser.',
  },
  {
    id: 't25d',
    sswFrom: 25,
    sswTo: 28,
    category: 'partnerschaft',
    emoji: '💑',
    text: 'Sprecht heute über eure Erwartungen ans Wochenbett. Wer kommt wann zu Besuch? Wer übernimmt welche Aufgaben? Früh reden spart Stress.',
    detail: 'Konkrete Themen: Wer geht einkaufen in den ersten zwei Wochen? Wer kocht? Wann kommt welche Familie zu Besuch — und wie lange? Wer redet mit den Schwiegereltern, wenn deren Erwartungen nicht passen? Klare Absprachen vor der Geburt verhindern Streit nach der Geburt — wenn ihr beide ohnehin müde und gereizt seid.',
  },
  {
    id: 't25e',
    sswFrom: 25,
    sswTo: 28,
    category: 'praktisch',
    emoji: '🪑',
    text: 'Beckenbodenübungen jetzt täglich — das macht später einen Riesenunterschied.',
    detail: 'Der Beckenboden trägt jetzt mehrere Kilo zusätzlich. Schon 5 Minuten täglich (anspannen, halten, lösen) wirken Wunder — gegen Inkontinenz nach der Geburt, für eine schnellere Rückbildung, für ein besseres Körpergefühl. Apps wie "Bauchgefühl" oder "Keep Calm Mama" haben gute Anleitungen. Beckenbodenkurse zahlt die Krankenkasse oft auch postnatal.',
  },

  // SSW 29–32 — Drittes Trimester
  {
    id: 't29a',
    sswFrom: 29,
    sswTo: 32,
    category: 'praktisch',
    emoji: '🏥',
    text: 'Jetzt wäre ein guter Zeitpunkt, das Krankenhaus oder Geburtshaus deiner Wahl zu besichtigen. Viele bieten Führungen an.',
    detail: 'Eine Kreißsaal-Führung nimmt eine Menge Angst. Du siehst die Räume, lernst typische Abläufe kennen und kannst Fragen stellen, die online nicht beantwortet werden: Darf ich essen? Wie viel Bewegung ist möglich? Was passiert wenn der Partner nicht rechtzeitig kommt? Die meisten Kliniken bieten Termine ab SSW 30 an — anrufen reicht.',
  },
  {
    id: 't29b',
    sswFrom: 29,
    sswTo: 32,
    category: 'mindset',
    emoji: '🌸',
    text: 'Ängste vor der Geburt sind menschlich. Sie bedeuten, dass du dir etwas wünschst — eine schöne Geburt, ein gesundes Baby, Kontrolle. Das ist verständlich.',
    detail: 'Angst ist keine Schwäche, sondern Information: Sie zeigt, was dir wichtig ist. Sprich mit deiner Hebamme darüber — sie kennt diese Sorgen, du musst sie nicht schön reden. Bei starken Ängsten gibt es spezialisierte Therapeuten (Geburtstrauma-Therapie, Hypnobirthing). Gut vorbereitet sein heißt nicht: keine Angst haben. Es heißt: trotz Angst handlungsfähig bleiben.',
  },
  {
    id: 't29c',
    sswFrom: 29,
    sswTo: 32,
    category: 'reflexion',
    emoji: '💭',
    text: 'Was sind deine drei wichtigsten Wünsche für die Geburt? Schreib sie in den Geburtsplan-Wizard — heute ist ein guter Tag dafür.',
    detail: 'Drei Punkte sind realistisch — bei 20 Wünschen wird es im Stress vergessen. Sortiere nach: was ist mir absolut heilig, was wäre schön, was ist mir relativ egal. Die wichtigsten 3 lernt dein Partner auswendig. So kann er/sie für dich sprechen, falls du in den Wehen nicht mehr willst oder kannst.',
  },
  {
    id: 't29d',
    sswFrom: 29,
    sswTo: 32,
    category: 'partnerschaft',
    emoji: '💑',
    text: 'Besprecht heute den Weg ins Krankenhaus. Wo liegt der Eingang? Wo kann man parken? Was tun um 3 Uhr nachts? Üben reduziert Stress.',
    detail: 'Fahrt einmal "trocken" hin — ohne Wehen. Wo ist die Notaufnahme? Wo der Kreißsaal-Eingang nachts? Gibt es einen Geburtsklingel? Speichert die Nummer ein. Macht ein Foto vom Eingang. Plant Plan B falls das Auto nicht startet (Taxi-Nummer, Nachbarin). Diese Vorbereitung dauert 30 Minuten und nimmt im Ernstfall enorm Druck raus.',
  },
  {
    id: 't29e',
    sswFrom: 29,
    sswTo: 32,
    category: 'mindset',
    emoji: '🕯️',
    text: 'Du brauchst keine "perfekte Geburt". Du brauchst nur eine, durch die du gut hindurch kommst.',
    detail: 'Geburten sind unberechenbar. Manchmal läuft alles wie auf Wolken, manchmal wird aus dem Wassergeburtsplan ein Notkaiserschnitt. Beide Geburten sind gültig. Beide bringen ein Baby auf die Welt. Beide machen dich zur Mutter. Lass los, was du nicht kontrollieren kannst — und halt fest, was du kannst (Vorbereitung, Atmung, Vertrauen ins Team).',
  },

  // SSW 33–36 — Nesting & Vorbereitung
  {
    id: 't33a',
    sswFrom: 33,
    sswTo: 36,
    category: 'praktisch',
    emoji: '🎒',
    text: 'Pack jetzt die Krankentasche. Für dich: Wäsche, Kosmetik, Snacks. Fürs Baby: Strampler, Mützchen, erste Windeln. Für den Partner: Verpflegung, Ladekabel.',
    detail: 'Stell die Tasche an die Wohnungstür oder ins Auto. Wichtig: Vergiss nicht ein bequemes Outfit für die Heimfahrt — Jeans passen nicht. Lippenpflege gegen ausgetrocknete Lippen während der Wehen, ein Lieblingstee, ein Foto, das dich ruhig macht. Eine Liste was zuletzt rein muss (Handy, Ladekabel, Mutterpass) klebt am besten an der Tasche.',
  },
  {
    id: 't33b',
    sswFrom: 33,
    sswTo: 36,
    category: 'mindset',
    emoji: '🏠',
    text: 'Der Nesting-Instinkt ist real: Das Bedürfnis, alles vorzubereiten und aufzuräumen, ist biologisch. Hör auf deinen Körper — aber überanstrenge dich nicht.',
    detail: 'Plötzlich willst du den Backofen putzen, das Babybett 5x umstellen, Schubladen ausmisten? Das ist millionenalter Instinkt — nicht Verrücktheit. Aber: keine Leiter, keine schweren Möbel, keine Chemikalien. Delegiere die anstrengenden Sachen an den Partner und konzentrier dich auf das, was sich ruhig anfühlt — sortieren, falten, ordnen.',
  },
  {
    id: 't33c',
    sswFrom: 33,
    sswTo: 36,
    category: 'reflexion',
    emoji: '🌺',
    text: 'Wer soll als Erstes informiert werden, wenn die Wehen beginnen? Leg heute eine kurze Anrufliste an — das macht es leichter.',
    detail: 'Drei Listen: 1) Wer wird sofort angerufen (Partner, Hebamme, Klinik). 2) Wer kommt in den ersten Stunden (Eltern, beste Freundin). 3) Wer wird nach der Geburt informiert (alle anderen). Schreib sie auf einen Zettel am Kühlschrank. Im Wehensturm denkt niemand klar — eine Liste rettet euch beide.',
  },
  {
    id: 't33d',
    sswFrom: 33,
    sswTo: 36,
    category: 'partnerschaft',
    emoji: '💑',
    text: 'Plant einen "letzten Abend zu zweit" — ein schönes Essen, ein Film, einfach füreinander da sein. Bald seid ihr zu dritt.',
    detail: 'Es ist nicht der "letzte" Abend — aber so wie es jetzt ist, wird es nie wieder sein. Spontane Restaurantbesuche, lange ausschlafen, ungestörte Gespräche — das wird seltener. Markiert diesen Moment bewusst. Schreibt euch je einen Brief, oder bewahrt einen kleinen Gegenstand auf — etwas, das ihr eurem Kind mal zeigen könnt.',
  },
  {
    id: 't33e',
    sswFrom: 33,
    sswTo: 36,
    category: 'praktisch',
    emoji: '🍲',
    text: 'Fang jetzt an, fürs Wochenbett vorzukochen — gefrorene Mahlzeiten sind Gold wert.',
    detail: 'In den ersten Wochen mit Baby kommst du nicht zum Kochen. Bereite jetzt 5-10 Portionen vor: Suppen, Currys, Eintöpfe, Lasagne — alles was sich gut einfrieren lässt. Stillende brauchen mehr Energie und besonders Eisen — Linsen, Hafer, dunkles Gemüse. Eine gut gefüllte Gefriertruhe ist eines der schönsten Geschenke an dein zukünftiges Ich.',
  },

  // SSW 37–39 — Endspurt
  {
    id: 't37a',
    sswFrom: 37,
    sswTo: 39,
    category: 'mindset',
    emoji: '✨',
    text: 'Dein Baby ist jetzt "offiziell reif". Es könnte jederzeit kommen — oder noch ein paar Wochen warten. Üb dich in Geduld und Vertrauen.',
    detail: 'Nur etwa 5% aller Babys kommen am errechneten Termin. Manche kommen 3 Wochen früher, manche 2 Wochen später — beides ist normal. Versuch loszulassen vom "Wann kommt es endlich?". Stattdessen: was kannst du heute Schönes tun? Cafe, Massage, Spaziergang. Diese ruhigen letzten Tage darfst du genießen, statt stündlich auf den Bauch zu schauen.',
  },
  {
    id: 't37b',
    sswFrom: 37,
    sswTo: 39,
    category: 'praktisch',
    emoji: '📱',
    text: 'Speicher die Nummer deiner Hebamme, des Kreißsaals und deines Partners an einem leicht zugänglichen Ort. Im Moment der Wehen suchst du nicht gern.',
    detail: 'Lege eine Favoriten-Gruppe in deinen Kontakten an: "Geburt". Hebamme, Klinik, Partner, beste Freundin, Eltern. Notiere zusätzlich auf einem Zettel am Kühlschrank — falls das Handy mal leer ist oder verloren geht. Wenn du den Wegweiser jetzt vorbereitest, brauchst du im Ernstfall nicht mehr nachzudenken.',
  },
  {
    id: 't37c',
    sswFrom: 37,
    sswTo: 39,
    category: 'reflexion',
    emoji: '💭',
    text: 'Was willst du dem Baby als erstes sagen? Manche Mütter üben es — andere lassen es einfach kommen. Was fühlt sich für dich richtig an?',
    detail: 'Manche flüstern den Namen, andere sagen "Hallo du", andere weinen einfach. Es gibt keine richtigen Worte — aber einen ersten Atemzug zusammen. Diese Sekunde wird dich für immer prägen. Wenn du dir vorher etwas zurechtlegen willst, mach das. Wenn du dich überraschen lassen willst, auch gut. Hauptsache: sei da.',
  },
  {
    id: 't37d',
    sswFrom: 37,
    sswTo: 39,
    category: 'partnerschaft',
    emoji: '💑',
    text: 'Euer Leben verändert sich bald für immer — zum Wunderschönen. Schreibt euch heute je einen Brief, den ihr nach der Geburt lest.',
    detail: 'Was wünscht du dir für euch als Eltern? Was schätzt du an deinem Partner besonders? Welche Versprechen wollt ihr euch geben? Diese Briefe sind kein Test, kein Versprechen, kein Vertrag — nur ein Schnappschuss eures Wir genau jetzt. In drei Jahren, mitten in einer Streitphase, werden sie unbezahlbar sein.',
  },
  {
    id: 't37e',
    sswFrom: 37,
    sswTo: 39,
    category: 'praktisch',
    emoji: '🚗',
    text: 'Babyschale jetzt einbauen lassen — du fährst damit nach Hause.',
    detail: 'Du darfst das Krankenhaus nicht ohne Babyschale verlassen. Lass den Einbau von einem Profi prüfen — ADAC, Babyfachmarkt oder zertifizierter Händler. Falsch eingebaute Babyschalen sind eine der häufigsten Sicherheitsmängel. Übe einmal: wie schnall ich ein Baby richtig an? (Gurt zwischen den Beinen, Riemen auf Schulterhöhe, kein dicker Anorak.)',
  },

  // SSW 40–42 — Übertragung / Warten
  {
    id: 't40a',
    sswFrom: 40,
    sswTo: 42,
    category: 'mindset',
    emoji: '🌙',
    text: 'Warten ist schwer. Dein Körper und dein Baby wissen, wann die Zeit gekommen ist. Du kannst vertrauen — auch wenn es sich nicht so anfühlt.',
    detail: 'Jeder Tag fühlt sich an wie eine Woche. Die Frage "und, schon was?" wird unerträglich. Tipp: Stell den Status auf "Wir melden uns wenn es soweit ist" und blocke die Frage damit ab. Verbring die Wartezeit mit Dingen, die dich runterfahren — Filme, Bücher, lange Bäder, Eis. Das Baby kommt sicher. Der ETT ist ein Schätzwert, kein Lieferdatum.',
  },
  {
    id: 't40b',
    sswFrom: 40,
    sswTo: 42,
    category: 'praktisch',
    emoji: '🚶‍♀️',
    text: 'Spaziergänge, Himbeerblättertee, Akupunktur — vieles wird empfohlen. Was sich für dich richtig anfühlt, ist das Richtige. Kein Druck.',
    detail: 'Bewährte Wehen-anregende Methoden: lange Spaziergänge (besonders Treppen rauf), warme Bäder, scharfes Essen, Sex (Prostaglandine im Sperma!), Akupunktur bei der Hebamme. Was nicht hilft: Stress, Frust, ständig auf den Bauch starren. Wenn die Geburt nicht beginnen will, hat das oft einen Grund — dein Körper, dein Baby brauchen noch Zeit.',
  },
  {
    id: 't40c',
    sswFrom: 40,
    sswTo: 42,
    category: 'reflexion',
    emoji: '🌸',
    text: 'Du hast diese Reise gemeistert. Jede Übelkeit, jede schlaflose Nacht, jede Sorge — du hast sie getragen. Das ist außergewöhnlich.',
    detail: '40 Wochen lang hast du einen Menschen wachsen lassen. Du hast Müdigkeit ausgehalten, Sodbrennen, Rückenschmerzen, Sorgen, Vorfreude. Du bist eine andere geworden, ohne es zu merken. Egal wie deine Geburt verläuft — diese 9 Monate haben dich vorbereitet. Du bist bereit. Auch wenn dein Kopf gerade etwas anderes sagt.',
  },
  {
    id: 't40d',
    sswFrom: 40,
    sswTo: 42,
    category: 'partnerschaft',
    emoji: '💑',
    text: 'Nutzt die letzten gemeinsamen Stunden: schlafen, essen, reden, kuscheln. Die Zeit zu zweit ist kostbar — und eine neue beginnt bald.',
    detail: 'Schaut euch alte Fotos an — von eurer ersten Wohnung, eurer Hochzeit, eurer ersten Reise. Erinnert euch, wer ihr wart, bevor ihr Eltern wurdet. Dieses Paar bleibt — auch wenn es bald in einer neuen Konstellation lebt. Eine starke Beziehung ist das größte Geschenk, das ihr eurem Kind machen könnt. Heute ist ein guter Tag, das zu spüren.',
  },
  {
    id: 't40e',
    sswFrom: 40,
    sswTo: 42,
    category: 'mindset',
    emoji: '⏳',
    text: 'Die letzten Tage sind oft die längsten. Sei sanft mit dir.',
    detail: 'Nichts in deinem ganzen Leben hat dich darauf vorbereitet, so lange auf etwas Unkontrollierbares zu warten. Du wirst ungeduldig, frustriert, vielleicht weinerlich — alles legitim. Halte dir vor Augen: in einer Woche, in zwei Wochen ist es vorbei. Dann hältst du dein Baby im Arm. Bis dahin: ein Tag nach dem anderen.',
  },
]

export function getTipForDay(ssw: number, date: Date = new Date()): Tip {
  const clampedSSW = Math.max(1, Math.min(42, ssw))
  const matching = TIPS.filter((t) => clampedSSW >= t.sswFrom && clampedSSW <= t.sswTo)
  const pool = matching.length > 0 ? matching : TIPS.filter((t) => t.sswFrom <= 4)
  const dayOfYear = Math.floor((date.getTime() - new Date(date.getFullYear(), 0, 0).getTime()) / 86400000)
  return pool[dayOfYear % pool.length]
}

export const CATEGORY_LABELS: Record<TipCategory, string> = {
  praktisch: 'Praktischer Tipp',
  mindset: 'Mindset-Impuls',
  partnerschaft: 'Für euch beide',
  reflexion: 'Gedankenanstoß',
}
