import type { LocalizedString } from '@/lib/i18n/localized'
import type { TerminCategory, TerminTypeDef } from './types'

export const TERMIN_TYPES: TerminTypeDef[] = [
  {
    id: 'erstgespraech',
    category: 'untersuchung',
    emoji: '👋',
    title: { de: 'Erstgespräch beim Frauenarzt', en: 'First consultation with gynecologist' },
    description: {
      de: 'Bestätigung der Schwangerschaft, Mutterpass-Anlage, Gesundheitsanamnese.',
      en: 'Confirmation of pregnancy, opening of Mutterpass, medical history.',
    },
    sswFrom: 5,
    sswTo: 8,
    oneOff: true,
    recommended: true,
  },
  {
    id: 'erste_vorsorge',
    category: 'untersuchung',
    emoji: '🩺',
    title: { de: '1. Vorsorgeuntersuchung', en: '1st prenatal check-up' },
    description: {
      de: 'Erste Routine-Untersuchung, Ultraschall, Bluttest.',
      en: 'First routine check, ultrasound, blood test.',
    },
    sswFrom: 9,
    sswTo: 12,
    oneOff: true,
    recommended: true,
  },
  {
    id: 'nackenfaltenmessung',
    category: 'untersuchung',
    emoji: '🔬',
    title: {
      de: 'Nackenfaltenmessung (Ersttrimester-Screening)',
      en: 'Nuchal translucency (first-trimester screening)',
    },
    description: {
      de: 'Optionale, kassenfreie Screening-Untersuchung zur Risikoeinschätzung.',
      en: 'Optional, self-pay screening to assess risk.',
    },
    sswFrom: 11,
    sswTo: 14,
    oneOff: true,
    recommended: true,
  },
  {
    id: 'triple_test',
    category: 'untersuchung',
    emoji: '🧪',
    title: { de: 'Triple-/Quadruple-Test (optional)', en: 'Triple/Quadruple test (optional)' },
    description: {
      de: 'Bluttest zur Risikoeinschätzung von Chromosomen-Abweichungen.',
      en: 'Blood test to assess chromosome anomaly risk.',
    },
    sswFrom: 14,
    sswTo: 20,
    oneOff: true,
    recommended: false,
  },
  {
    id: 'feindiagnostik',
    category: 'untersuchung',
    emoji: '🔍',
    title: { de: 'Feindiagnostik (großer Ultraschall)', en: 'Anomaly scan (detailed ultrasound)' },
    description: {
      de: 'Detaillierter Ultraschall: Organe, Größe, Geschlecht.',
      en: 'Detailed ultrasound: organs, size, sex.',
    },
    sswFrom: 19,
    sswTo: 22,
    oneOff: true,
    recommended: true,
  },
  {
    id: 'zuckertest',
    category: 'untersuchung',
    emoji: '🍬',
    title: { de: 'Glukosetoleranztest (Zuckertest)', en: 'Glucose tolerance test' },
    description: {
      de: 'Test auf Schwangerschaftsdiabetes.',
      en: 'Screening for gestational diabetes.',
    },
    sswFrom: 24,
    sswTo: 28,
    oneOff: true,
    recommended: true,
  },
  {
    id: 'dritter_ultraschall',
    category: 'untersuchung',
    emoji: '📸',
    title: { de: '3. großer Ultraschall', en: '3rd major ultrasound' },
    description: {
      de: 'Wachstumskontrolle, Lage des Babys, Plazenta-Check.',
      en: 'Growth check, baby position, placenta check.',
    },
    sswFrom: 29,
    sswTo: 32,
    oneOff: true,
    recommended: true,
  },
  {
    id: 'ctg',
    category: 'untersuchung',
    emoji: '💓',
    title: { de: 'CTG (Kardiotokographie)', en: 'CTG (cardiotocography)' },
    description: {
      de: 'Aufzeichnung der Herztöne und Wehentätigkeit. Mehrfach in der Spätschwangerschaft.',
      en: 'Recording of heartbeat and contractions. Multiple times in late pregnancy.',
    },
    sswFrom: 30,
    sswTo: 42,
    oneOff: false,
    recommended: true,
  },
  {
    id: 'hebammengespraech',
    category: 'beratung',
    emoji: '💛',
    title: { de: 'Hebammengespräch', en: 'Midwife consultation' },
    description: {
      de: 'Erstes Treffen mit deiner Wochenbett-Hebamme.',
      en: 'First meeting with your postpartum midwife.',
    },
    sswFrom: 28,
    sswTo: 36,
    oneOff: true,
    recommended: true,
  },
  {
    id: 'geburtsplangespraech',
    category: 'beratung',
    emoji: '📋',
    title: { de: 'Geburtsplangespräch', en: 'Birth plan consultation' },
    description: {
      de: 'Besprechung deiner Wünsche mit Hebamme oder Klinik.',
      en: 'Discuss your wishes with midwife or clinic.',
    },
    sswFrom: 32,
    sswTo: 38,
    oneOff: true,
    recommended: true,
  },
  {
    id: 'klinikbesichtigung',
    category: 'vorbereitung',
    emoji: '🏥',
    title: { de: 'Klinikbesichtigung / Anmeldung', en: 'Hospital tour / pre-registration' },
    description: {
      de: 'Klinik anschauen und für die Geburt anmelden.',
      en: 'Visit the hospital and pre-register for birth.',
    },
    sswFrom: 30,
    sswTo: 36,
    oneOff: true,
    recommended: true,
  },
  {
    id: 'wochenbett_hebamme',
    category: 'vorbereitung',
    emoji: '🤱',
    title: { de: 'Wochenbett-Hebamme organisieren', en: 'Arrange postpartum midwife' },
    description: {
      de: 'Eine Hebamme für die ersten Wochen nach der Geburt suchen — oft 6+ Monate Vorlauf!',
      en: 'Find a midwife for the first weeks after birth — often 6+ months in advance!',
    },
    sswFrom: 16,
    sswTo: 28,
    oneOff: true,
    recommended: true,
  },
  {
    id: 'geburtsvorbereitung',
    category: 'vorbereitung',
    emoji: '🧘',
    title: { de: 'Geburtsvorbereitungskurs', en: 'Childbirth preparation course' },
    description: {
      de: 'Mehrwöchiger Kurs zu Atemtechniken, Wehen, Geburt.',
      en: 'Multi-week course on breathing, labor, birth.',
    },
    sswFrom: 25,
    sswTo: 35,
    oneOff: true,
    recommended: true,
  },
  {
    id: 'stillberatung',
    category: 'vorbereitung',
    emoji: '🍼',
    title: { de: 'Stillvorbereitungs-Beratung', en: 'Breastfeeding preparation' },
    description: {
      de: 'Optional: Beratung zum Stillen, Pumpen, ersten Tagen.',
      en: 'Optional: breastfeeding, pumping, first days.',
    },
    sswFrom: 30,
    sswTo: 38,
    oneOff: true,
    recommended: false,
  },
  {
    id: 'zahnarzt',
    category: 'sonstiges',
    emoji: '🦷',
    title: { de: 'Zahnarzt-Vorsorge', en: 'Dental check-up' },
    description: {
      de: 'In der SS empfohlen — kassenübernahme.',
      en: 'Recommended during pregnancy — covered by insurance.',
    },
    sswFrom: 12,
    sswTo: 32,
    oneOff: true,
    recommended: true,
  },
]

export const CATEGORY_LABELS: Record<TerminCategory, LocalizedString> = {
  untersuchung: { de: 'Untersuchungen', en: 'Examinations' },
  beratung: { de: 'Beratungen', en: 'Consultations' },
  vorbereitung: { de: 'Vorbereitung', en: 'Preparation' },
  sonstiges: { de: 'Sonstiges', en: 'Other' },
}
